remote_theme: "jekyll/minima@c6e74bb"

author: Flattop5377
email: Flattop5377@proton.me
description: >
  A wrapper for a pure netfilter without iptables firewall that is easy to
  install and maintain with Ansible.

github_username: Flattop5377
rss: rss

plugins:
  - jekyll-feed
  - jekyll-seo-tag
