title: afirewall - A Pure Netfilter Firewall
email: flattop5377@proton.me
description: >- # this means to ignore newlines until "baseurl:"
  afirewall is a wrapper for a pure netfilter - no iptables - firewall that is
  easy to configure with ansible's lineinfile module
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
  #twitter_username: jekyllrb
github_username: flattop5377

# Build settings
plugins:
  - jekyll-feed

theme: "minima"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
